CREATE TABLE Anime { anime_id INT NOT NULL PRIMARY KEY,
title VARCHAR(30),
media_image TEXT,
created_at DATE,
episodes INT,
};
CREATE TABLE Movies { movie_id INT NOT NULL PRIMARY KEY,
title VARCHAR(30),
media_image TEXT,
created_at DATE,
};
CREATE TABLE Songs { song_id INT NOT NULL PRIMARY KEY,
title VARCHAR(30),
author VARCHAR(30),
album VARCHAR(30),
media_image TEXT,
created_at DATE,
};
CREATE TYPE Platforms AS ENUM { 'nintendo-switch',
'nintendo-wiiu',
'nintendo-wii',
'nintendo-gamecube',
'nintendo-64',
'ps5',
'ps4',
'ps3',
'ps2',
'xbox-x',
'xbox-s',
'xbox-one',
'xbox' } CREATE TABLE VideoGames { video_game_id INT NOT NULL PRIMARY KEY,
title VARCHAR(30),
media_image TEXT,
created_on DATE,
platform Platforms NOT NULL,
};